// Default rules by language. Keep keywords largely language-agnostic.
(function () {
  const rules_zhCN = [
    { category: '开源与代码托管', keywords: ['github', 'gitlab', 'gitee', 'bitbucket', 'source code', 'repository', 'repo'] },
    { category: '开发文档与API', keywords: ['docs', 'documentation', 'api', 'sdk', 'developer', 'developers', 'reference', '文档', '接口'] },
    { category: '前端框架', keywords: ['react', 'vue', 'angular', 'svelte', 'nextjs', 'nuxt', 'vite', 'webpack', 'babel', 'preact', 'solidjs', 'ember'] },
    { category: '后端框架', keywords: ['spring', 'springboot', 'django', 'flask', 'fastapi', 'express', 'koa', 'rails', 'laravel', 'nestjs', 'micronaut', 'quarkus', 'fastify', 'hapi', 'gin', 'asp.net', 'dotnet', 'phoenix'] },
    { category: '云服务与DevOps', keywords: ['aws', 'azure', 'gcp', 'cloud', 'kubernetes', 'k8s', 'docker', 'ci', 'cd', 'devops', 'terraform', 'cloudflare', 'vercel', 'netlify', 'digitalocean', 'heroku', 'render', 'linode', 'railway'] },
    { category: '数据库与数据', keywords: ['mysql', 'postgres', 'mongodb', 'redis', 'sqlite', 'elasticsearch', 'clickhouse', 'snowflake', 'data', '数据库', 'mariadb', 'oracle', 'sql server', 'mssql', 'dynamodb', 'bigquery', 'firestore', 'cassandra'] },
    { category: '数据科学与分析', keywords: ['kaggle', 'jupyter', 'databricks', 'data science', '数据科学', 'pandas', 'numpy'] },
    { category: 'API测试与开发', keywords: ['postman', 'insomnia', 'swagger', 'openapi', 'api 测试'] },
    { category: 'AI与机器学习', keywords: ['ai', 'ml', 'deep learning', 'transformer', 'openai', 'huggingface', 'stable diffusion', 'llm', '机器学习', 'tensorflow', 'pytorch'] },
    { category: '产品设计', keywords: ['product', 'ux', 'ui', 'prototype', '设计', '交互', '体验'] },
    { category: '设计资源与素材', keywords: ['dribbble', 'behance', 'figma', 'psd', 'svg', 'icon', 'font', '素材', '配色', 'icons8', 'fontawesome', 'coolors', 'colorhunt'] },
    { category: '学习教程与课程', keywords: ['course', '教程', 'tutorial', 'learn', '学习', 'udemy', 'coursera', 'edx', 'pluralsight', 'codecademy', 'freecodecamp'] },
    { category: '技术博客与社区', keywords: ['blog', '博客', 'medium', 'dev.to', 'reddit', '讨论', 'community', '论坛', 'hashnode'] },
    { category: '新闻资讯与媒体', keywords: ['news', '资讯', 'headline', '媒体', 'press', 'newsletter', 'techcrunch', 'hacker news', 'wired', 'theverge'] },
    { category: '在线工具与服务', keywords: ['tool', '工具', 'software', 'app', '应用', 'utility', 'converter', 'online', 'remove.bg', 'smallpdf', 'ilovepdf', 'tinypng', 'tinyurl'] },
    { category: '下载与资源', keywords: ['download', '下载', '镜像', '资源', 'release', 'npmjs', 'pypi', 'maven', 'rubygems', 'crates.io'] },
    { category: '视频与音乐', keywords: ['youtube', 'bilibili', 'netflix', 'spotify', 'video', '音乐', '音频', 'vimeo', 'soundcloud', 'apple music'] },
    { category: '游戏与娱乐', keywords: ['game', 'gaming', 'steam', 'xbox', 'ps5', '游戏', '娱乐', 'epic', 'uplay', 'origin', 'battlenet', 'psn', 'nintendo'] },
    { category: '购物电商', keywords: ['shop', '购物', 'buy', '购买', 'store', '商店', 'mall', '商城', 'taobao', 'jd', 'amazon', 'aliexpress', 'etsy', 'ebay', 'shopify'] },
    { category: '社交媒体', keywords: ['twitter', 'x.com', 'facebook', 'instagram', 'tiktok', 'linkedin', '社交', '分享', '社区', 'discord', 'telegram'] },
    { category: '办公与协作', keywords: ['notion', 'confluence', 'slack', 'teams', 'jira', 'office', '文档', '协作', 'drive', 'google drive', 'dropbox', 'onedrive', 'monday', 'miro'] },
    { category: '笔记与知识库', keywords: ['obsidian', 'evernote', 'note', 'wiki', '知识库'] },
    { category: '项目与任务管理', keywords: ['asana', 'trello', 'todoist', 'clickup', 'kanban', '项目管理', '任务'] },
    { category: '地图与导航', keywords: ['google maps', 'maps', 'gaode', '高德', 'baidu map', '百度地图', 'openstreetmap', 'osm', '导航'] },
    { category: '博客平台与CMS', keywords: ['wordpress', 'ghost', 'blogger', 'cms', '内容管理'] },
    { category: '邮件与通讯', keywords: ['gmail', 'outlook', 'mail', '邮箱', 'imap', 'smtp', 'message', 'chat', 'protonmail', 'fastmail', 'zoho mail', 'mailchimp', 'sendgrid'] },
    { category: '求职与招聘', keywords: ['jobs', '招聘', '求职', 'career', 'hr', '猎头', '简历', 'indeed', 'glassdoor', 'lever', 'greenhouse', '拉勾', 'boss直聘', '前程无忧'] },
    { category: '金融与理财', keywords: ['bank', 'finance', '投资', '基金', '股票', 'trading', 'crypto', '区块链', 'paypal', 'stripe', 'alipay', 'wechat pay', 'wise'] },
    { category: '生活服务', keywords: ['生活', '服务', '家政', '外卖', '出行', '住宿', '旅游', 'uber', 'didi', '美团', '饿了么', 'airbnb', 'booking', 'trip', 'expedia'] },
    { category: '阅读与电子书', keywords: ['read', '阅读', '电子书', 'epub', 'pdf', 'kindle', 'goodreads', 'gutenberg', 'scribd'] },
    { category: '科研与论文', keywords: ['arxiv', '论文', 'research', '科研', 'paper', 'citation', 'nature', 'science', 'springer', 'ieee', 'acm', 'doi', 'researchgate'] },
    { category: '浏览器与扩展', keywords: ['extension', '插件', 'chrome web store', 'edge add-ons', '浏览器', 'addons.mozilla.org', 'opera addons'] },
    { category: '摄影与照片', keywords: ['photography', 'photo', '照片', '攝影', 'camera', '拍照', '拍摄'] },
    { category: '图片处理与修图', keywords: ['lightroom', 'photoshop', 'capture one', '修图', '编辑', 'raw', '后期', '色彩', 'affinity photo', 'gimp', 'luminar'] },
    { category: '器材与评测', keywords: ['dslr', 'mirrorless', '微单', '单反', '镜头', 'lens', '评测', 'review', 'dxomark', 'cameralabs'] },
    { category: '图片托管与分享', keywords: ['flickr', '500px', 'unsplash', 'pixabay', 'pexels', '图库', 'portfolio', '作品集', '图床', 'imgur', 'pixiv'] },
    { category: '摄影品牌与官网', keywords: ['canon', 'nikon', 'sonyalpha', 'fujifilm', 'leica', 'sigma', 'tamron', '富士', '徕卡'] },
    { category: '器材评测与资讯', keywords: ['dpreview', 'petapixel', 'fstoppers', '评测', '测评', '资讯'] },
    { category: '版权素材与购买', keywords: ['getty', 'gettyimages', 'shutterstock', 'adobe stock', 'istock', 'pond5', '版权', '素材购买'] },
    { category: '摄影教程与灵感', keywords: ['教程', 'tips', 'composition', '构图', '布光', '灵感', 'inspiration', 'kelbyone', 'phlearn'] },
  ];

  const rules_zhTW = [
    { category: '開源與代碼託管', keywords: ['github', 'gitlab', 'gitee', 'bitbucket', 'source code', 'repository', 'repo'] },
    { category: '開發文檔與API', keywords: ['docs', 'documentation', 'api', 'sdk', 'developer', 'developers', 'reference', '文件', '介面'] },
    { category: '前端框架', keywords: ['react', 'vue', 'angular', 'svelte', 'nextjs', 'nuxt', 'vite', 'webpack', 'babel', 'preact', 'solidjs', 'ember'] },
    { category: '後端框架', keywords: ['spring', 'springboot', 'django', 'flask', 'fastapi', 'express', 'koa', 'rails', 'laravel', 'nestjs', 'micronaut', 'quarkus', 'fastify', 'hapi', 'gin', 'asp.net', 'dotnet', 'phoenix'] },
    { category: '雲服務與DevOps', keywords: ['aws', 'azure', 'gcp', 'cloud', 'kubernetes', 'k8s', 'docker', 'ci', 'cd', 'devops', 'terraform', 'cloudflare', 'vercel', 'netlify', 'digitalocean', 'heroku', 'render', 'linode', 'railway'] },
    { category: '資料庫與資料', keywords: ['mysql', 'postgres', 'mongodb', 'redis', 'sqlite', 'elasticsearch', 'clickhouse', 'snowflake', 'data', '資料庫', 'mariadb', 'oracle', 'sql server', 'mssql', 'dynamodb', 'bigquery', 'firestore', 'cassandra'] },
    { category: '數據科學與分析', keywords: ['kaggle', 'jupyter', 'databricks', 'data science', '數據科學', 'pandas', 'numpy'] },
    { category: 'API測試與開發', keywords: ['postman', 'insomnia', 'swagger', 'openapi', 'api 測試'] },
    { category: 'AI與機器學習', keywords: ['ai', 'ml', 'deep learning', 'transformer', 'openai', 'huggingface', 'stable diffusion', 'llm', '機器學習', 'tensorflow', 'pytorch'] },
    { category: '產品設計', keywords: ['product', 'ux', 'ui', 'prototype', '設計', '互動', '體驗'] },
    { category: '設計資源與素材', keywords: ['dribbble', 'behance', 'figma', 'psd', 'svg', 'icon', 'font', '素材', '配色', 'icons8', 'fontawesome', 'coolors', 'colorhunt'] },
    { category: '學習教程與課程', keywords: ['course', '教程', 'tutorial', 'learn', '學習', 'udemy', 'coursera', 'edx', 'pluralsight', 'codecademy', 'freecodecamp'] },
    { category: '技術博客與社區', keywords: ['blog', '博客', 'medium', 'dev.to', 'reddit', '社群', 'community', '論壇', 'hashnode'] },
    { category: '新聞資訊與媒體', keywords: ['news', '資訊', 'headline', '媒體', 'press', 'newsletter', 'techcrunch', 'hacker news', 'wired', 'theverge'] },
    { category: '在線工具與服務', keywords: ['tool', '工具', 'software', 'app', '應用', 'utility', 'converter', 'online', 'remove.bg', 'smallpdf', 'ilovepdf', 'tinypng', 'tinyurl'] },
    { category: '下載與資源', keywords: ['download', '下載', '鏡像', '資源', 'release', 'npmjs', 'pypi', 'maven', 'rubygems', 'crates.io'] },
    { category: '影片與音樂', keywords: ['youtube', 'bilibili', 'netflix', 'spotify', 'video', '音樂', '音訊', 'vimeo', 'soundcloud', 'apple music'] },
    { category: '遊戲與娛樂', keywords: ['game', 'gaming', 'steam', 'xbox', 'ps5', '遊戲', '娛樂', 'epic', 'uplay', 'origin', 'battlenet', 'psn', 'nintendo'] },
    { category: '購物電商', keywords: ['shop', '購物', 'buy', '購買', 'store', '商店', 'mall', '商城', 'taobao', 'jd', 'amazon', 'aliexpress', 'etsy', 'ebay', 'shopify'] },
    { category: '社交媒體', keywords: ['twitter', 'x.com', 'facebook', 'instagram', 'tiktok', 'linkedin', '社交', '分享', '社群', 'discord', 'telegram'] },
    { category: '辦公與協作', keywords: ['notion', 'confluence', 'slack', 'teams', 'jira', 'office', '文件', '協作', 'drive', 'google drive', 'dropbox', 'onedrive', 'monday', 'miro'] },
    { category: '筆記與知識庫', keywords: ['obsidian', 'evernote', 'note', 'wiki', '知識庫'] },
    { category: '專案與任務管理', keywords: ['asana', 'trello', 'todoist', 'clickup', 'kanban', '專案管理', '任務'] },
    { category: '地圖與導航', keywords: ['google maps', 'maps', 'gaode', '高德', 'baidu map', '百度地圖', 'openstreetmap', 'osm', '導航'] },
    { category: '部落格平台與CMS', keywords: ['wordpress', 'ghost', 'blogger', 'cms', '內容管理'] },
    { category: '郵件與通訊', keywords: ['gmail', 'outlook', 'mail', '郵箱', 'imap', 'smtp', 'message', 'chat', 'protonmail', 'fastmail', 'zoho mail', 'mailchimp', 'sendgrid'] },
    { category: '求職與招聘', keywords: ['jobs', '招聘', '求職', 'career', 'hr', '獵頭', '履歷', 'indeed', 'glassdoor', 'lever', 'greenhouse'] },
    { category: '金融與理財', keywords: ['bank', 'finance', '投資', '基金', '股票', 'trading', 'crypto', '區塊鏈', 'paypal', 'stripe', 'alipay', 'wechat pay', 'wise'] },
    { category: '生活服務', keywords: ['生活', '服務', '家政', '外送', '出行', '住宿', '旅遊', 'uber', 'airbnb', 'booking'] },
    { category: '閱讀與電子書', keywords: ['read', '閱讀', '電子書', 'epub', 'pdf', 'kindle', 'goodreads', 'gutenberg'] },
    { category: '科研與論文', keywords: ['arxiv', '論文', 'research', '科研', 'paper', 'citation', 'nature', 'science', 'springer', 'ieee', 'acm'] },
    { category: '瀏覽器與擴充', keywords: ['extension', '外掛', 'chrome web store', 'edge add-ons', 'addons.mozilla.org'] },
    { category: '攝影與照片', keywords: ['photography', 'photo', '照片', '攝影', 'camera'] },
    { category: '圖片處理與修圖', keywords: ['lightroom', 'photoshop', 'capture one', '修圖', '編輯', 'raw', '後期'] },
    { category: '器材與評測', keywords: ['dslr', 'mirrorless', '微單', '單反', '鏡頭', 'lens', '評測', 'review', 'dxomark', 'cameralabs'] },
    { category: '圖片託管與分享', keywords: ['flickr', '500px', 'unsplash', 'pixabay', 'pexels', '圖庫', '作品集', '圖床', 'imgur', 'pixiv'] },
    { category: '攝影品牌與官網', keywords: ['canon', 'nikon', 'sonyalpha', 'fujifilm', 'leica', 'sigma', 'tamron'] },
    { category: '器材評測與資訊', keywords: ['dpreview', 'petapixel', 'fstoppers', '評測', '資訊'] },
    { category: '版權素材與購買', keywords: ['getty', 'gettyimages', 'shutterstock', 'adobe stock', 'istock', 'pond5', '版權', '素材購買'] },
    { category: '攝影教程與靈感', keywords: ['教程', 'tips', 'composition', '構圖', '布光', '靈感', 'inspiration', 'kelbyone', 'phlearn'] },
  ];

  const rules_en = [
    { category: 'Open Source & Code Hosting', keywords: ['github', 'gitlab', 'bitbucket', 'source code', 'repository', 'repo'] },
    { category: 'Developer Docs & APIs', keywords: ['docs', 'documentation', 'api', 'sdk', 'developer', 'developers', 'reference'] },
    { category: 'Frontend Frameworks', keywords: ['react', 'vue', 'angular', 'svelte', 'nextjs', 'nuxt', 'vite', 'webpack', 'babel', 'preact', 'solidjs', 'ember'] },
    { category: 'Backend Frameworks', keywords: ['spring', 'springboot', 'django', 'flask', 'fastapi', 'express', 'koa', 'rails', 'laravel', 'nestjs', 'micronaut', 'quarkus', 'fastify', 'hapi', 'gin', 'asp.net', 'dotnet', 'phoenix'] },
    { category: 'Cloud & DevOps', keywords: ['aws', 'azure', 'gcp', 'cloud', 'kubernetes', 'k8s', 'docker', 'ci', 'cd', 'devops', 'terraform', 'cloudflare', 'vercel', 'netlify', 'digitalocean', 'heroku', 'render', 'linode', 'railway'] },
    { category: 'Databases & Data', keywords: ['mysql', 'postgres', 'mongodb', 'redis', 'sqlite', 'elasticsearch', 'clickhouse', 'snowflake', 'data', 'mariadb', 'oracle', 'sql server', 'mssql', 'dynamodb', 'bigquery', 'firestore', 'cassandra'] },
    { category: 'Data Science & Analytics', keywords: ['kaggle', 'jupyter', 'databricks', 'data science', 'pandas', 'numpy'] },
    { category: 'API Testing & Development', keywords: ['postman', 'insomnia', 'swagger', 'openapi'] },
    { category: 'AI & Machine Learning', keywords: ['ai', 'ml', 'deep learning', 'transformer', 'openai', 'huggingface', 'stable diffusion', 'llm', 'tensorflow', 'pytorch'] },
    { category: 'Product Design', keywords: ['product', 'ux', 'ui', 'prototype', 'design'] },
    { category: 'Design Resources & Assets', keywords: ['dribbble', 'behance', 'figma', 'psd', 'svg', 'icon', 'font', 'icons8', 'fontawesome', 'coolors', 'colorhunt'] },
    { category: 'Tutorials & Courses', keywords: ['course', 'tutorial', 'learn', 'udemy', 'coursera', 'edx', 'pluralsight', 'codecademy', 'freecodecamp'] },
    { category: 'Tech Blogs & Communities', keywords: ['blog', 'medium', 'dev.to', 'reddit', 'community', 'forum', 'hashnode'] },
    { category: 'News & Media', keywords: ['news', 'headline', 'press', 'newsletter', 'techcrunch', 'hacker news', 'wired', 'theverge'] },
    { category: 'Online Tools & Services', keywords: ['tool', 'software', 'app', 'utility', 'converter', 'online', 'remove.bg', 'smallpdf', 'ilovepdf', 'tinypng', 'tinyurl'] },
    { category: 'Downloads & Packages', keywords: ['download', 'mirror', 'release', 'npmjs', 'pypi', 'maven', 'rubygems', 'crates.io'] },
    { category: 'Video & Music', keywords: ['youtube', 'netflix', 'spotify', 'video', 'audio', 'vimeo', 'soundcloud', 'apple music'] },
    { category: 'Games & Entertainment', keywords: ['game', 'gaming', 'steam', 'xbox', 'ps5', 'epic', 'uplay', 'origin', 'battlenet', 'psn', 'nintendo'] },
    { category: 'Shopping & E‑commerce', keywords: ['shop', 'buy', 'store', 'mall', 'amazon', 'aliexpress', 'etsy', 'ebay', 'shopify'] },
    { category: 'Social Media', keywords: ['twitter', 'x.com', 'facebook', 'instagram', 'tiktok', 'linkedin', 'discord', 'telegram'] },
    { category: 'Office & Collaboration', keywords: ['notion', 'confluence', 'slack', 'teams', 'jira', 'docs', 'drive', 'google drive', 'dropbox', 'onedrive', 'monday', 'miro'] },
    { category: 'Notes & Knowledge Bases', keywords: ['obsidian', 'evernote', 'note', 'wiki'] },
    { category: 'Project & Task Management', keywords: ['asana', 'trello', 'todoist', 'clickup', 'kanban', 'project', 'task'] },
    { category: 'Maps & Navigation', keywords: ['google maps', 'maps', 'openstreetmap', 'osm', 'gaode', 'baidu map'] },
    { category: 'Blogging & CMS', keywords: ['wordpress', 'ghost', 'blogger', 'cms'] },
    { category: 'Email & Communication', keywords: ['gmail', 'outlook', 'mail', 'imap', 'smtp', 'message', 'chat', 'protonmail', 'fastmail', 'zoho mail', 'mailchimp', 'sendgrid'] },
    { category: 'Jobs & Recruiting', keywords: ['jobs', 'career', 'hr', 'resume', 'indeed', 'glassdoor', 'lever', 'greenhouse'] },
    { category: 'Finance & Investing', keywords: ['bank', 'finance', 'investing', 'fund', 'stock', 'trading', 'crypto', 'blockchain', 'paypal', 'stripe', 'wise'] },
    { category: 'Life Services', keywords: ['food delivery', 'rides', 'travel', 'uber', 'airbnb', 'booking', 'expedia'] },
    { category: 'Reading & eBooks', keywords: ['read', 'ebook', 'epub', 'pdf', 'kindle', 'goodreads', 'gutenberg', 'scribd'] },
    { category: 'Research & Papers', keywords: ['arxiv', 'paper', 'research', 'citation', 'nature', 'science', 'springer', 'ieee', 'acm', 'doi', 'researchgate'] },
    { category: 'Browsers & Extensions', keywords: ['extension', 'chrome web store', 'edge add-ons', 'addons.mozilla.org'] },
    { category: 'Photography & Photos', keywords: ['photography', 'photo', 'camera'] },
    { category: 'Image Editing', keywords: ['lightroom', 'photoshop', 'capture one', 'raw', 'editing', 'color', 'affinity photo', 'gimp', 'luminar'] },
    { category: 'Gear & Reviews', keywords: ['dslr', 'mirrorless', 'lens', 'review', 'dxomark', 'cameralabs'] },
    { category: 'Photo Hosting & Sharing', keywords: ['flickr', '500px', 'unsplash', 'pixabay', 'pexels', 'portfolio', 'imgur', 'pixiv'] },
    { category: 'Camera Brands', keywords: ['canon', 'nikon', 'sonyalpha', 'fujifilm', 'leica', 'sigma', 'tamron'] },
    { category: 'Gear Reviews & News', keywords: ['dpreview', 'petapixel', 'fstoppers'] },
    { category: 'Stock Assets & Purchase', keywords: ['getty', 'gettyimages', 'shutterstock', 'adobe stock', 'istock', 'pond5', 'stock'] },
    { category: 'Photo Tutorials & Inspiration', keywords: ['tutorial', 'tips', 'composition', 'lighting', 'inspiration', 'kelbyone', 'phlearn'] },
  ];

  const rules_ru = [
    { category: 'Открытый код и хостинг', keywords: ['github', 'gitlab', 'bitbucket', 'репозиторий', 'repo'] },
    { category: 'Документация и API', keywords: ['docs', 'documentation', 'api', 'sdk', 'developer', 'reference'] },
    { category: 'Фронтенд-фреймворки', keywords: ['react', 'vue', 'angular', 'svelte', 'nextjs', 'nuxt', 'vite', 'webpack', 'babel', 'preact', 'solidjs', 'ember'] },
    { category: 'Бэкенд-фреймворки', keywords: ['spring', 'springboot', 'django', 'flask', 'fastapi', 'express', 'koa', 'rails', 'laravel', 'nestjs', 'micronaut', 'quarkus', 'fastify', 'hapi', 'gin', 'asp.net', 'dotnet', 'phoenix'] },
    { category: 'Облако и DevOps', keywords: ['aws', 'azure', 'gcp', 'cloud', 'kubernetes', 'k8s', 'docker', 'ci', 'cd', 'devops', 'terraform', 'cloudflare', 'vercel', 'netlify', 'digitalocean', 'heroku', 'render', 'linode', 'railway'] },
    { category: 'Базы данных и данные', keywords: ['mysql', 'postgres', 'mongodb', 'redis', 'sqlite', 'elasticsearch', 'clickhouse', 'snowflake', 'data', 'mariadb', 'oracle', 'sql server', 'mssql', 'dynamodb', 'bigquery', 'firestore', 'cassandra'] },
    { category: 'Дата-сайенс и аналитика', keywords: ['kaggle', 'jupyter', 'databricks', 'data science', 'pandas', 'numpy'] },
    { category: 'Тестирование и разработка API', keywords: ['postman', 'insomnia', 'swagger', 'openapi'] },
    { category: 'ИИ и машинное обучение', keywords: ['ai', 'ml', 'deep learning', 'transformer', 'openai', 'huggingface', 'stable diffusion', 'llm', 'tensorflow', 'pytorch'] },
    { category: 'Дизайн продукта', keywords: ['product', 'ux', 'ui', 'prototype', 'design'] },
    { category: 'Дизайн-ресурсы и ассеты', keywords: ['dribbble', 'behance', 'figma', 'psd', 'svg', 'icon', 'font', 'icons8', 'fontawesome', 'coolors', 'colorhunt'] },
    { category: 'Обучение и курсы', keywords: ['course', 'tutorial', 'learn', 'udemy', 'coursera', 'edx', 'pluralsight', 'codecademy', 'freecodecamp'] },
    { category: 'Тех-блоги и сообщества', keywords: ['blog', 'medium', 'dev.to', 'reddit', 'community', 'forum', 'hashnode'] },
    { category: 'Новости и СМИ', keywords: ['news', 'headline', 'press', 'newsletter', 'techcrunch', 'hacker news', 'wired', 'theverge'] },
    { category: 'Онлайн-инструменты и сервисы', keywords: ['tool', 'software', 'app', 'utility', 'converter', 'online', 'remove.bg', 'smallpdf', 'ilovepdf', 'tinypng', 'tinyurl'] },
    { category: 'Загрузки и ресурсы', keywords: ['download', 'mirror', 'release', 'npmjs', 'pypi', 'maven', 'rubygems', 'crates.io'] },
    { category: 'Видео и музыка', keywords: ['youtube', 'netflix', 'spotify', 'video', 'audio', 'vimeo', 'soundcloud', 'apple music'] },
    { category: 'Игры и развлечения', keywords: ['game', 'gaming', 'steam', 'xbox', 'ps5', 'epic', 'uplay', 'origin', 'battlenet', 'psn', 'nintendo'] },
    { category: 'Покупки и e‑commerce', keywords: ['shop', 'buy', 'store', 'mall', 'amazon', 'aliexpress', 'etsy', 'ebay', 'shopify'] },
    { category: 'Социальные сети', keywords: ['twitter', 'x.com', 'facebook', 'instagram', 'tiktok', 'linkedin', 'discord', 'telegram'] },
    { category: 'Офис и совместная работа', keywords: ['notion', 'confluence', 'slack', 'teams', 'jira', 'docs', 'drive', 'google drive', 'dropbox', 'onedrive', 'monday', 'miro'] },
    { category: 'Заметки и базы знаний', keywords: ['obsidian', 'evernote', 'note', 'wiki'] },
    { category: 'Проекты и задачи', keywords: ['asana', 'trello', 'todoist', 'clickup', 'kanban', 'project', 'task'] },
    { category: 'Карты и навигация', keywords: ['google maps', 'maps', 'openstreetmap', 'osm', 'gaode', 'baidu map'] },
    { category: 'Блоги и CMS', keywords: ['wordpress', 'ghost', 'blogger', 'cms'] },
    { category: 'Почта и коммуникации', keywords: ['gmail', 'outlook', 'mail', 'imap', 'smtp', 'message', 'chat', 'protonmail', 'fastmail', 'zoho mail', 'mailchimp', 'sendgrid'] },
    { category: 'Работа и найм', keywords: ['jobs', 'career', 'hr', 'resume', 'indeed', 'glassdoor', 'lever', 'greenhouse'] },
    { category: 'Финансы и инвестиции', keywords: ['bank', 'finance', 'investing', 'fund', 'stock', 'trading', 'crypto', 'blockchain', 'paypal', 'stripe', 'wise'] },
    { category: 'Бытовые сервисы', keywords: ['food delivery', 'rides', 'travel', 'uber', 'airbnb', 'booking', 'expedia'] },
    { category: 'Чтение и электронные книги', keywords: ['read', 'ebook', 'epub', 'pdf', 'kindle', 'goodreads', 'gutenberg'] },
    { category: 'Наука и статьи', keywords: ['arxiv', 'paper', 'research', 'citation', 'nature', 'science', 'springer', 'ieee', 'acm'] },
    { category: 'Браузеры и расширения', keywords: ['extension', 'chrome web store', 'edge add-ons', 'addons.mozilla.org'] },
    { category: 'Фотография и фото', keywords: ['photography', 'photo', 'camera'] },
    { category: 'Обработка изображений', keywords: ['lightroom', 'photoshop', 'capture one', 'raw', 'editing', 'color', 'affinity photo', 'gimp', 'luminar'] },
    { category: 'Оборудование и обзоры', keywords: ['dslr', 'mirrorless', 'lens', 'review', 'dxomark', 'cameralabs'] },
    { category: 'Хостинг и обмен фото', keywords: ['flickr', '500px', 'unsplash', 'pixabay', 'pexels', 'portfolio', 'imgur', 'pixiv'] },
    { category: 'Бренды камер', keywords: ['canon', 'nikon', 'sonyalpha', 'fujifilm', 'leica', 'sigma', 'tamron'] },
    { category: 'Обзоры и новости оборудования', keywords: ['dpreview', 'petapixel', 'fstoppers'] },
    { category: 'Стоковые материалы и покупка', keywords: ['getty', 'gettyimages', 'shutterstock', 'adobe stock', 'istock', 'pond5', 'stock'] },
    { category: 'Туториалы и вдохновение по фото', keywords: ['tutorial', 'tips', 'composition', 'lighting', 'inspiration', 'kelbyone', 'phlearn'] },
  ];

  function byLang(lang) {
    if (!lang) return rules_en;
    const l = lang.toLowerCase();
    if (l.startsWith('zh-tw')) return rules_zhTW;
    if (l.startsWith('zh')) return rules_zhCN;
    if (l.startsWith('ru')) return rules_ru;
    return rules_en;
  }

  window.DefaultRules = {
    get(lang) {
      return byLang(lang).map(r => ({ category: r.category, keywords: r.keywords.slice() }));
    }
  };
})();